name: pharmacy
services:
  backend:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
  database:
    image: mongo:6.0.12-jammy
    ports:
      - 27017:27017
    volumes:
      - mydb:/data/db
volumes:
  mydb:
